version: 0.2

env:
  variables:
    ARTIFACT_S3_BUCKET: "example-bucket"

phases:
  install:
    commands:
      - cd helloWorldExample
      - npm install
  build:
    commands:
      - npm run build
      - sam package --template-file template.yml --s3-bucket ${ARTIFACT_S3_BUCKET} --output-template-file packaged-template.yml
artifacts:
  files:
    - 'packaged-template.yml'
  base-directory: 'helloWorldExample'
