version: 0.2

phases:
  install:
    commands:
      - cd helloWorldExample && npm install
  build:
    commands:
      - cd helloWorldExample && npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'helloWorldExample/build'
